In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [6]:
vals = np.linspace(-10, 10, num=100, dtype=np.float32)
activation = sigmoid(vals)
fig = plt.figure(figsize=(12, 6))
plt.plot(vals, activation)
plt.grid(True, which='both')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.yticks()
plt.ylim([-0.5, 1.5])

(-0.5, 1.5)

In [8]:
def logic_gate(w1, w2, b):
    # Helper to create logic gate functions
    # Plug in values for weight_a, weight_b, and bias
    return lambda x1, x2: sigmoid(w1 * x1 + w2 * x2 + b)

def test(gate):
    # Helper function to test out our weight functions.
    for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
        print("{}, {}: {}".format(a, b, np.round(gate(a, b))))


In [10]:
or_gate = logic_gate(20, 20, -10)
test(or_gate)

and_gate = logic_gate(15,15, -20)
test(and_gate)



0, 0: 0.0
0, 1: 1.0
1, 0: 1.0
1, 1: 1.0
0, 0: 0.0
0, 1: 0.0
1, 0: 0.0
1, 1: 1.0


In [12]:
nor_gate = logic_gate(0, 0, 0)
test(nor_gate)

nand_gate = logic_gate(0, 0, 0)
test(nand_gate)


0, 0: 0.0
0, 1: 0.0
1, 0: 0.0
1, 1: 0.0
0, 0: 0.0
0, 1: 0.0
1, 0: 0.0
1, 1: 0.0


In [14]:
def xor_gate(a, b):
    c = or_gate(a, b)
    d = nand_gate(a, b)
    return and_gate(c, d)
test(xor_gate)



0, 0: 0.0
0, 1: 1.0
1, 0: 1.0
1, 1: 1.0


In [16]:
W_1 = np.random.randn(4, 3)
W_2 = np.random.randn(5, 4)
W_3 = np.random.randn(3, 5)


In [18]:
# Single input vector (3 features)
x_in = np.array([0.5, 0.3, 0.2])

# 7 input samples (each row is a sample of size 3)
x_mat_in = np.random.rand(7, 3)


In [20]:
def soft_max_vec(x):
    """Softmax for single vector"""
    e_x = np.exp(x - np.max(x))  # numerical stability
    return e_x / np.sum(e_x)

def soft_max_mat(x):
    """Row-wise softmax for matrix"""
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))  # numerical stability
    return e_x / np.sum(e_x, axis=1, keepdims=True)


In [22]:
def forward_pass_single(x, W_1, W_2, W_3, return_intermediates=False):
    z1 = np.dot(W_1, x)
    a1 = sigmoid(z1)

    z2 = np.dot(W_2, a1)
    a2 = sigmoid(z2)

    z3 = np.dot(W_3, a2)
    a3 = soft_max_vec(z3)

    if return_intermediates:
        return z1, a1, z2, a2, z3, a3
    return a3

In [24]:

def forward_pass_batch(X, W_1, W_2, W_3):
    z1 = X @ W_1.T
    a1 = sigmoid(z1)

    z2 = a1 @ W_2.T
    a2 = sigmoid(z2)

    z3 = a2 @ W_3.T
    a3 = soft_max_mat(z3)

    return a3

In [26]:
print("\n----- Single Input Output with Intermediates -----")
z1, a1, z2, a2, z3, a3 = forward_pass_single(x_in, W_1, W_2, W_3, return_intermediates=True)
print("Layer 1 input (z1):", z1)
print("Layer 1 output (a1):", a1)
print("Layer 2 input (z2):", z2)
print("Layer 2 output (a2):", a2)
print("Output layer input (z3):", z3)
print("Output softmax (a3):", a3)

print("\n----- Batch Input Output -----")
print(forward_pass_batch(x_mat_in, W_1, W_2, W_3))


----- Single Input Output with Intermediates -----
Layer 1 input (z1): [-0.6271461   0.5756988   0.6017554  -0.01806911]
Layer 1 output (a1): [0.34815793 0.6400771  0.64605781 0.49548285]
Layer 2 input (z2): [0.54230081 0.63149612 1.16590677 0.40685107 0.09690433]
Layer 2 output (a2): [0.63234748 0.65282863 0.76240435 0.60033258 0.52420714]
Output layer input (z3): [-2.50392657  1.02238436 -1.76768329]
Output softmax (a3): [0.02696407 0.91673289 0.05630304]

----- Batch Input Output -----
[[0.02713717 0.92076052 0.05210231]
 [0.03379583 0.91678424 0.04941993]
 [0.03367016 0.9165995  0.04973035]
 [0.03264368 0.9098424  0.05751391]
 [0.02703653 0.91622278 0.05674069]
 [0.03066921 0.92001255 0.04931824]
 [0.03078148 0.91446316 0.05475535]]
